<template>
  <main>
    <h2>Instructions</h2>
    <h3>What this is</h3>
    <p>
      This tool is for people who want to improve their English spelling. You will hear a sentence
      and try to type it into the text area. It uses the built-in TTS of your OS and Browser, so the
      quality of playback might vary. All the sentences were auto-generated by
      <span class="highlight">ChatGPT 3.5</span> (Please report any mistakes). This project is
      written using TypeScript and Vue.
    </p>
    <h3>Rules</h3>
    <ul>
      <li>All the sentences should be in <span class="highlight">American English</span>.</li>
      <li>Mind the capitalization. Start your sentences with a capital letter.</li>
      <li>You will be presented with only one sentence at a time.</li>
      <li>
        Ending punctuation is <span class="highlight">omitted</span>, you don't need to add
        <span class="highlight">'.!?'</span>
      </li>
      <li>
        You will loop through all the sentences in the exercise until you get them all correct.
      </li>
      <li>
        You can leave and return to the exercise at any time, your
        <span class="highlight">progress will be saved</span>.
      </li>
      <li>Progress is saved in your browser. You can freely reload the page.</li>
      <li>During the first speech playback, you will hear a preview.</li>
      <li>
        You can adjust the speed of preview and regular speech in the
        <span class="highlight">settings menu</span>.
      </li>
      <li>You can add a small delay between words for regular speech playback.</li>
      <li>This delay might vary based on your OS and Browser.</li>
      <li>Some mobile devices might not support pausing the speech.</li>
    </ul>
  </main>
</template>

<style scoped>
h2,
h3 {
  text-decoration: underline;
  margin-top: 1rem;
}

h3 {
  color: var(--primary-good);
}

p {
  margin: 0 5%;
}

.highlight {
  color: var(--primary-highlight);
}
</style>
